on:
  push:
    branches: [ "feature/continuous-integration", "development" ]

jobs:
  devel:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - run: pacman-key --init
      - run: pacman -Syu --noconfirm git sudo
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory /__w/cagebreak/cagebreak
      - run: bash scripts/install-development-environment
      - run: meson setup build -Dxwayland=true -Dman-pages=true --buildtype=release
      - run: ninja -C build
      - run: meson test -C build --suite devel --suite devel-long -v
  basic:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - run: pacman-key --init
      - run: pacman -Syu --noconfirm git sudo
      - uses: actions/checkout@v3
      - run: bash scripts/install-development-environment
      - run: meson setup build -Dxwayland=true -Dman-pages=true --buildtype=release
      - run: ninja -C build
      - run: useradd test && usermod -L test
      - run: runuser -l test -c 'meson test -C build --suite basic -v'
  release:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - run: pacman-key --init
      - run: pacman -Syu --noconfirm git sudo
      - uses: actions/checkout@v3
      - run: bash scripts/install-development-environment
      - run: meson setup build -Dxwayland=true -Dman-pages=true --buildtype=release
      - run: ninja -C build
      - run: useradd test && usermod -L test
      - run: runuser -l test -c 'meson test -C build --suite release -v'


#  pkgtest:
#    runs-on: ubuntu-latest
#    container:
#      image: archlinux:latest
#    steps:
#      - run: pacman-key --init
#      - run: pacman -Syu --noconfirm git sudo
#      - run: git clone https://github.com/project-repo/cagebreak-pkgbuild
#      - run: cd cagebreak-pkgbuild/cagebreak
#      - run: makepkg
